### ISSUE TITLE
%% placeholder is not working in exclusion clauses

### ISSUE THREAD

**Issue by ak0rz** [ADTRAN/gradle-scala-multiversion-plugin#17]
Hello,

Consider this dependency clause

```
dependencies {
    compile(group: 'io.monix', name: 'monix_%%', version: '3.0.0-RC2') {
        exclude group: 'org.typelevel', module: 'cats-effect_%%'
    }
}
```

scala-multiversion-plugin does not replace placeholder in exclusion clause which leads to this result in resulting pom.xml

```
    <dependency>
      <groupId>io.monix</groupId>
      <artifactId>monix_2.11</artifactId>
      <version>3.0.0-RC2</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>cats-effect_%%</artifactId>
          <groupId>org.typelevel</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

which is incorrect.
I haven't dive deep enough in groovy and plugin code, is it hard to fix this issue?

**Comment by nathanalderson** [comment]
So I tried to look into this some. I can't figure out where the exclude rules get stored or how to influence their processing. The plugin uses `conf.resolutionStrategy.eachDependency {...}` to influence the dependency resolution, but the `DependencyResolveDetails` object that the handler receives doesn't seem to include exclusion rules. If you or someone knows how to get to those it should be possible to apply the substitution rules similar to the way we do for dependencies.

It's not as pretty, but you should be able to use `$scalaSuffix` instead of `_%%`. This seemed to work for me in a quick test:

    compile('io.monix:monix_%%:+') {
        exclude group: 'org.typelevel', module: "cats-effect$scalaSuffix"
    }

Thanks for pointing this out.

**Comment by nathanalderson** [comment]
Closing this issue for now. Even in latest versions of Gradle I don't see how to get to these exclusion rules and I believe there's a viable workaround.
