### ISSUE TITLE
%scala-version% placeholder does not work when not in version position

### ISSUE THREAD

**Issue by pierangeloc** [ADTRAN/gradle-scala-multiversion-plugin#24]
When using `%scala-version%` outside a version position (e.g. as required by some Scala compiler plugins, the translation is not applied, e.g.

```
        scalaCompilerPlugin "org.scalamacros:paradise_%scala-version%:2.1.0"
```
is translated to `repository/public/org/scalamacros/paradise_%25scala-version%25/2.1.0/paradise_%25scala-version%25-2.1.0.pom` that can't be found

When the same placeholder is used in a version position, it works fine, as in 
```
        implementation("org.scala-lang:scala-library:%scala-version%")
```

**Comment by nathanalderson** [comment]
This is by design, but I wasn't aware of this use case. I don't think it would hurt to do the substitution in the name field as well.

If you're interested in raising a PR, the relevant change would be [here](https://github.com/ADTRAN/gradle-scala-multiversion-plugin/blob/master/src/main/groovy/com/adtran/ScalaMultiVersionPlugin.groovy#L86-L91). To verify that it works, add a new dependency like you describe to the [test project dependencies](https://github.com/ADTRAN/gradle-scala-multiversion-plugin/blob/master/testProjects/simpleProject/build.gradle#L35-L39) and add an empty file that matches to the [fake repo](https://github.com/ADTRAN/gradle-scala-multiversion-plugin/tree/master/testProjects/simpleProject/fakeRepo).

Thanks for the report!
