### ISSUE TITLE
Submodules built with a subset of Scala versions?

### ISSUE THREAD

**Issue by bzamecnik** [ADTRAN/gradle-scala-multiversion-plugin#4]
Is it possible to specify that some submodule should be built only for a subset of Scala versions (eg. root module with 2.10-2.12 and a submodule just 2.10)? Or in other words exclude a project based on the Scala version. Thanks.

**Comment by bzamecnik** [comment]
Maybe the answer is "For multi-project builds, it is recommended to apply the plugin individually to each relevant project/subproject." (from README). It'll try that.

**Comment by bzamecnik** [comment]
There's also: "Building subprojects for different versions of scala is not supported."

How difficult do you think it might be to support this?

**Comment by nathanalderson** [comment]
Thanks for the question. As you noted from the readme, at the moment, there is no way to build different submodules for different versions. Unfortunately, I think this would take some effort to add because the plugin today just pulls the scalaVersions from the root project properties and then schedules a new `GradleBuild` task for each version using the same tasks that were specified on the command line.

The workaround for now would be to call the subprojects separately and use the command line to select the verions you want to run. Something like this:

In your root `gradle.properties`:

```
scalaVersions = 2.11.8, 2.12.1
```

From the command line:

```
# build subproject1 for all versions
> ./gradlew :subproject1:build
# build subproject2 for only 2.11.8
> ./gradlew :subproject2:build -PscalaVersions=2.11.8
```

Closing for now. Feel free to reopen if you have further questions.

**Comment by bzamecnik** [comment]
Thanks for a reply. Actually in the end I solved the problem by plain gradle without any plugins. I call nested builds for each scala version, but in `settings.gradle` include only module compatible with the given version. It's not perfect but works. It's not aligned perfectly with Gradle philosophy that all modules should be included. Better would be conditionally enable/disable tasks in the nested build.

**Comment by radimk** [comment]
FWIW I have a use case that is similar to @bzamecnik's: some sub-projects are plain Java, some are heavily reused Java/Scala code compatible with 2.10 and 2.11, and then there are sub-projects that are 2.10 or 2.11 specific (for examle Spark 1.6 or Spark 2.0 jobs that require specific Scala version). I expect that I will end up with a setup where one Gradle invocation is anchored to one Scala version and builds only subset of sub-projects.

**Comment by tomnis** [comment]
Sorry for the necrobump but I wanted to chime in with our similar use case:

Some of our dependencies are unfortunately not cross compiled, only built for 2.12. We want to isolate our usage of those in a separate subproject and cross-compile our core project
