### ISSUE TITLE
Generated Gradle Module Metadata contains  %% placeholders

### ISSUE THREAD

**Issue by blondacz** [ADTRAN/gradle-scala-multiversion-plugin#41]
Generated Gradle Module Metadata contains %% placeholders instead of scala base version. The generated pom file is correct.

**Comment by nathanalderson** [comment]
Happy to review a pull request, but otherwise this probably won't get looked at.

**Comment by Shamann** [comment]
I've run into an issue when built an app dependent on an open-source library whose maintainer used this plugin. It happened so that I needed a custom build of the library, so I built it and published to a local maven repository and then build my app (which was a separate project, not a part of a multi-project gradle build). The build failed because gradle didn't manage to properly resolve the library's dependencies containing %% placeholder.
Here are two work-arounds I found in case someone faces a similar situation before the plugin is patched:

1. Use the plugin to build your app. With multiversion plugin applied gradle is able to resolve the dependencies and app is built successfully.
2. If you are able to configure the dependency's build, you can disable gradle metadata publication like [this](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication)
`tasks.withType(GenerateModuleMetadata) {
     enabled = false
}`
After that gradle will use maven's pom file with correct dependencies' versions.
